name: Upload release to GitHub Package

# Run this workflow when a tag is pushed
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    name: Release build and updload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Upload release to GitHub Package
        run: ./gradlew publishMavenPublicationToGitHubPackagesRepository --no-daemon --no-parallel
        env:
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          TOKEN: ${{secrets.RELEASE_TOKEN}}
          USERNAME: ${{secrets.GITHUB_ACTOR}}